/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package src;

public class App {
    public static void main(String[] args) {
        Game game = new Game();
        game.gameInit();

    }
}
