/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package src;

public class App {
    public static void main(String[] args) {
        Chessboard chessboard = new Chessboard();
        chessboard.fillBoard();
        chessboard.drawBoard();
    }
}
